version: "2"

networks:
  default:
      external:
        name: "web"

services:
  whotraefik:
    image: "traefik:v2.6"
    container_name: "whotraefik"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whofrontend:
    build:
      context: "."
      dockerfile: "./.docker/frontend/Dockerfile"
    container_name: "whofrontend"
    volumes:
      - ./frontend:/app
    environment:
      - "API_BASEURI=http://api.whoowesme.local"
      - "APP_PORT=8000"
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.whofrontend.rule=Host(`whoowesme.local`)"
      - "traefik.http.services.whofrontend.loadBalancer.server.port=8000"
      - "traefik.http.routers.whofrontend.entrypoints=web"
    command: "npm run dev"
    tty: true

  whoapi:
    container_name: "whoapi"
    build:
      context: "."
      dockerfile: "./.docker/backend/Dockerfile"
    volumes:
      - './backend:/app'
    ports:
      - "5001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.whobackend.rule=Host(`api.whoowesme.local`)"
      - "traefik.http.services.whobackend.loadBalancer.server.port=5001"
      - "traefik.http.routers.whobackend.entrypoints=web"
      # Service Loadbalancer configs
      # Healthcheck
      # - "traefik.http.services.whobackend.loadBalancer.healthcheck.path=/health"
      # - "traefik.http.services.whobackend.loadBalancer.healthcheck.interval=60s"
      # - "traefik.http.services.whobackend.loadBalancer.healthcheck.timeout=10s"
    command: "npm run start:dev"
    tty: true
    environment:
      POSTGRES_HOST: "whodb"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db_whoowesme"
      FRONTEND_ORIGIN: "*"
      JWT_TOKEN_EXPIRES: "3h"
      JWT_SECRETS: "MySecretJWT"

  whodb:
    image: "postgres:12.3"
    container_name: "whodb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db_whoowesme"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    volumes:
      - "whodata:/var/lib/postgres/data"

  whodbtest:
    image: "postgres:12.3"
    container_name: "whodbtest"
    ports:
      - "5423:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db_whoowesmetest"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=web"
    # volumes:
    #   - "whodata:/var/lib/postgres/data"

volumes:
  whodata:
    external: true

