version: "2"

networks:
  default:
      external:
        name: "web"

services:
  whotraefik:
    image: "traefik:v2.3"
    container_name: "whotraefik"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  who-frontend:
    build:
      context: "."
      dockerfile: "./.docker/frontend/Dockerfile"
    container_name: "who-frontend"
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules:/app/node_modules"
    environment:
      - "REACT_APP_API_BASEURI=http://api.whoowesme.local"
      - "REACT_APP_ENV=development"
    ports:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.whofrontend.rule=Host(`whoowesme.local`)"
      - "traefik.http.services.whofrontend.loadBalancer.server.port=8000"
      - "traefik.http.routers.whofrontend.entrypoints=web"
    command: "npm run start"
    tty: "true"

  who-api:
    container_name: "who-api"
    build:
      context: "."
      dockerfile: "./.docker/backend/Dockerfile"
    volumes:
      - "./backend:/app"
      - "./backend/node_modules:/app/node_modules"
    ports:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.whobackend.rule=Host(`api.whoowesme.local`)"
      - "traefik.http.services.whobackend.loadBalancer.server.port=5000"
      - "traefik.http.routers.whobackend.entrypoints=web"
      # Service Loadbalancer configs
      # Healthcheck
      - "traefik.http.services.whobackend.loadBalancer.healthcheck.path=/health"
      - "traefik.http.services.whobackend.loadBalancer.healthcheck.interval=60s"
      - "traefik.http.services.whobackend.loadBalancer.healthcheck.timeout=10s"
    command: "npm run start:dev"
    tty: true

  who-db:
    image: "postgres:12.3"
    container_name: "who-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "db_whoowesme"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
    volumes:
      - "who-data:/var/lib/postgres/data"

volumes:
  who-data:
    external: true

