version: 2.1
orbs:
  node: circleci/node@4.2.0

jobs:
  build:
    environment:
      NODE_ENV: "development"

    steps:
      - checkout

      - node/install:
          install-yarn: false

      - run:
          name: "Files inside src folder"
          command: ls -al src/

      - run:
          name: Build
          command: ./.circleci/build.sh

workflows:
  # version: 2
  build-branch:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
